### ISSUE TITLE
White background under icon and title of item selected in a fragment layout

### ISSUE THREAD

**Issue by rMarduk87** [st235/ExpandableBottomBar#94]
Hi, I have a question about using the BottomBar in a fragment, I tried both with my own icons and with those of the example app by creating the menu programmatically and I noticed the same problem, that is, that the background of the icons and titles appears differently white color, i.e. the icon and the title are "illuminated" by the color but this overlaps with the white

Screen

Activity
<img width="320" alt="Screenshot 2023-09-21 alle 18 35 09" src="https://github.com/st235/ExpandableBottomBar/assets/30796324/ffb629ac-61a5-4c07-9676-a133a809d0d8">

Fragment

<img width="348" alt="Screenshot 2023-09-21 alle 18 34 10" src="https://github.com/st235/ExpandableBottomBar/assets/30796324/2dcd11bd-3de8-459f-8ca4-5c4f3518cfd1">

**Comment by st235** [comment]
Hello @rMarduk87 

Thank you for using the library!

It looks like an issue, indeed.

Can you, please, help me a bit and provide a minimal reproducible example to check out the issue myself? Just an app with activity, fragment, and resources you are using should be enough. I would really appreciate the collaboration on the issue.

Best regards,
Alex

**Comment by rMarduk87** [comment]
Hello this is my example
https://github.com/rMarduk87/TestBottomBar/tree/master

I saw what the problem is in my layout in the component I inserted this line android:theme="@style/BottomBarInfo"

**Comment by st235** [comment]
Thank you, I will take a look at the issue shortly

**Comment by st235** [comment]
Hello @rMarduk87 

I check out the project you've provided, thank you so much for doing so!

I can confirm that the issues comes from using `android:theme` in

```xml
    <github.com.st235.lib_expandablebottombar.ExpandableBottomBar
        android:id="@+id/expandable_bottom_bar3"
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        android:layout_marginTop="300dp"
        app:exb_backgroundCornerRadius="25dp"
        android:theme="@style/BottomBarInfo"
        app:exb_backgroundColor="@color/white"
        app:exb_itemInactiveColor="@color/black"
        app:exb_notificationBadgeBackgroundColor="@color/teal_200"
        app:exb_notificationBadgeTextColor="#FFFFFF"
        app:layout_constraintTop_toBottomOf="@+id/expandable_bottom_bar2"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintStart_toStartOf="parent" />
```

The problem is that `android:theme` when specified applies to the **view and its children**, therefore `android:background` has been applied to the elements inside.

If you remove this line (`andrioid:theme`) everythin should work just fine (see the image attached)

![Screenshot 2023-09-25 at 18 27 46](https://github.com/st235/ExpandableBottomBar/assets/14966197/bf2967bd-a024-4404-a65e-bb269292ae93)

If you want to change the background color of the `ExpandableBottomBar` you can use `app:exb_backgroundColor` attribute. 
Does it answer you question?

**Comment by rMarduk87** [comment]
@st235
Hi, thank you very much, it works perfectly now

**Comment by st235** [comment]
Glad to hear that!
